version: "3.8"

services:
  medicareapi:
    build:
      context: . 
      dockerfile: Dockerfile  
    ports:
      - "8080:8080"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Production  
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Username=admin;Password=admin;Database=MediCare
    depends_on:
      - database

  database:
    container_name: Database
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: MediCare
    ports:
      - "5432:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata:
    driver: local